#!/bin/bash

FORCE=~/oxDNA_UTILS/forces

echo ---------------------------------------------
echo ------- preparing data for simulation -------
echo ---------------------------------------------

#start_pos.txt ready

echo °°°°°°°°° start configurations °°°°°°°°°°°°°°
python2.7 ~/oxDNA_UTILS/UTILS/generate-new.py 30 seq.dat
echo °°°°°°°° end start configurations °°°°°°°°°°°

mv generated.dat start.conf
mv generated.top top.top

echo °°°°°°°°°° forces files °°°°°°°°°°°°°°°°°°°°°

#traps to make strands closer one to each other - or to make strands closer to a given point
python harm_trap.py #generate trapharm.txt
python mut_trap.py #generate trapmut.txt and trapcaps.txt

python $FORCE/generate_nico.py trapharm.txt harm_trap # generate harmonic_traps.txt 
python $FORCE/generate_nico.py trapmut.txt mut_trap # generate mut_traps.txt
python $FORCE/generate_nico.py trapcaps.txt caps_trap # generate caps_traps.txt

cat harmonic_traps.txt mut_traps.txt caps_traps.txt > forces.txt

echo °°°°°°°°° end forces files °°°°°°°°°°°°°°°°°°

echo ---------------------------------------------
echo ----------------- DONE ----------------------
echo ---------------------------------------------
